apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: argocd-management
value: 100000
globalDefault: false
preemptionPolicy: Never
description: Reserve scheduling priority for GitOps management without preempting
  application Pods.
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argocd-server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argocd-repo-server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argocd-redis-ha-haproxy
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis-ha-haproxy
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argocd-redis-ha-server
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis-ha
