apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: konomitv-data
  namespace: app-konomitv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: konomitv-recorded-pv
spec:
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.20.192
    path: /mnt/raid1_case/recorded
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=600
    - retrans=3
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: konomitv-recorded
  namespace: app-konomitv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  volumeName: konomitv-recorded-pv
  storageClassName: ""
