version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker/mirakurun"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/docker/encode-worker"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
