---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared # Assuming a dedicated namespace for cloudflared
data:
  config.yaml: |
    tunnel: TUNNEL_ID_PLACEHOLDER
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2006
    no-autoupdate: true
    ingress:
      - hostname: rancher.miutaku.work
        service: https://rancher-service.cattle-system.svc.cluster.local:443 # Assuming Rancher service name and namespace
        originRequest:
          noTLSVerify: true
      - hostname: wol.miutaku.work
        service: http://gptwol-service.app-gptwol.svc.cluster.local:5000 # Assuming gptwol service name and namespace
      - service: http_status:404
