apiVersion: batch/v1
kind: CronJob
metadata:
  name: annict-rec-sync-tnlastation
  namespace: app-annict-rec-sync-tnlastation
spec:
  schedule: "20 18 * * *"  # 03:20 JST 相当 (UTC)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: annict-rec-sync-tnlastation
              env:
                - name: EPGSTATION_BASE_URL
                  value: http://backend.app-tnlastation-staging.svc.cluster.local:8080
                - name: DRY_RUN
                  value: "true"
