apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: notifications-discord-webhook
  namespace: argocd
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-reventer-stg
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Merge
  data:
  - secretKey: discord-webhook-url
    remoteRef:
      key: REVENTER_DISCORD_WEBHOOK_URL
