apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-image-updater-secret
  namespace: argocd
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: ghcr-image-updater-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"miutaku","password":"{{
          .pat }}","auth":"{{ list "miutaku" .pat | join ":" | b64enc }}"}}}'
      engineVersion: v2
      mergePolicy: Replace
    deletionPolicy: Retain
  data:
  - secretKey: pat
    remoteRef:
      key: GITHUB_REVENTER_RUNNER_PAT
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
