apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- project.yaml
- reventer-stg.yaml
- reventer-admin-prd.yaml
- reventer-monitoring.yaml
- reventer-prd.yaml
- reventer-monitoring-prd.yaml
- argo-rollouts-prd.yaml
- secret-store.yaml
- external-secret-image-updater-ghcr.yaml
- external-secret-notifications-discord.yaml
- notifications.yaml
