apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reventer-monitoring
  namespace: argocd
spec:
  project: reventer
  source:
    repoURL: git@github.com:miutaku/reventer.git
    targetRevision: main
    path: infrastructure/k8s/monitoring
    kustomize:
      patches:
      - target:
          group: apps
          version: v1
          kind: Deployment
          name: vmagent
          namespace: reventer-monitoring
        patch: |-
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: vmagent
            namespace: reventer-monitoring
          spec:
            template:
              spec:
                nodeSelector:
                  reventer.io/capacity: base
                  node.info/compartment.id: aaaaaaaad2w76kjuhq54uhczukiz3qa3jdvhc6awmof73fi7jrlyrsjvgflq
  destination:
    namespace: reventer-monitoring
    name: oke-stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
