apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reventer-stg
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.discord: ''
spec:
  project: reventer
  source:
    repoURL: git@github.com:miutaku/reventer.git
    targetRevision: main
    path: infrastructure/k8s/stg
    kustomize:
      patches:
      - target:
          group: apps
          version: v1
          kind: Deployment
          name: cluster-autoscaler
          namespace: kube-system
        patch: |-
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: cluster-autoscaler
            namespace: kube-system
          spec:
            template:
              spec:
                nodeSelector:
                  reventer.io/capacity: base
                  node.info/compartment.id: aaaaaaaad2w76kjuhq54uhczukiz3qa3jdvhc6awmof73fi7jrlyrsjvgflq
                containers:
                - name: cluster-autoscaler
                  command:
                  - ./cluster-autoscaler
                  - --v=4
                  - --stderrthreshold=info
                  - --cloud-provider=oci
                  - --cloud-config=/etc/cluster-autoscaler/cloud-config/oci.conf
                  - --max-node-provision-time=25m
                  - --node-group-auto-discovery=clusterId:ocid1.cluster.oc1.ap-tokyo-1.aaaaaaaaxroxdjngbtuj63b3rqlczoidrjvu2cnlpqv7euzi6cl7a5hbbwnq,compartmentId:ocid1.compartment.oc1..aaaaaaaa4ho3i3ycitvc6bbtuqwuvehxirhu4uvy3f5pk3lp5qwxzul7tg6q,nodepoolTags:managed-by=terraform&environment=stg&capacity=burst,min:0,max:1
                  - --scale-down-delay-after-add=10m
                  - --scale-down-unneeded-time=10m
                  - --skip-nodes-with-system-pods=false
                  - --unremovable-node-recheck-timeout=5m
                  - --balance-similar-node-groups
                  - --balancing-ignore-label=displayName
                  - --balancing-ignore-label=hostname
                  - --balancing-ignore-label=internal_addr
                  - --balancing-ignore-label=oci.oraclecloud.com/fault-domain
      - target:
          group: apps
          version: v1
          kind: Deployment
          name: admin-tunnel
          namespace: app-reventer-stg
        patch: |-
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: admin-tunnel
            namespace: app-reventer-stg
          spec:
            strategy:
              type: RollingUpdate
              rollingUpdate:
                maxSurge: 1
                maxUnavailable: 0
            template:
              spec:
                nodeSelector:
                  reventer.io/capacity: base
                  node.info/compartment.id: aaaaaaaad2w76kjuhq54uhczukiz3qa3jdvhc6awmof73fi7jrlyrsjvgflq
                containers:
                - name: cloudflared
                  image: docker.io/cloudflare/cloudflared@sha256:9b49eed8f62806d5d45ddf59ecefb5710429598ea6d3fcccd2af938f621b2b07
                  readinessProbe:
                    httpGet:
                      path: /ready
                      port: 2000
                    initialDelaySeconds: 10
                    periodSeconds: 5
                    timeoutSeconds: 2
                    failureThreshold: 6
  destination:
    namespace: app-reventer-stg
    name: oke-stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: backend
    jsonPointers:
    - /spec/replicas
  - group: apps
    kind: Deployment
    name: frontend
    jsonPointers:
    - /spec/replicas
  - group: apps
    kind: Deployment
    name: admin
    jsonPointers:
    - /spec/replicas
