apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reventer-monitoring
  namespace: argocd
spec:
  project: reventer
  source:
    repoURL: git@github.com:miutaku/reventer.git
    targetRevision: main
    path: infrastructure/k8s/monitoring
  destination:
    namespace: reventer-monitoring
    name: oke-stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
