apiVersion: v1
kind: Namespace
metadata:
  name: talos-poc-node-exporter
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Pod
metadata:
  name: metrics-client
  namespace: talos-poc-node-exporter
spec:
  containers:
    - name: client
      image: busybox:1.37.0
      command:
        - sh
        - -c
        - sleep 3600
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
  restartPolicy: Never
