apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pve-exporter-config
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: pve-exporter-config
    creationPolicy: Owner
    template:
      data:
        # pve-exporter が読み込む設定ファイルを Secret として生成
        pve.yml: |
          default:
            user: root@pam
            token_name: "{{ .token_id }}"
            token_value: "{{ .token_secret }}"
            verify_ssl: false
  data:
    - secretKey: token_id
      remoteRef:
        key: PVE_MONITORING_TOKEN_ID
    - secretKey: token_secret
      remoteRef:
        key: PVE_MONITORING_TOKEN_SECRET
