---
- name: Added k8s bin directory to system-wide PATH
  ansible.builtin.lineinfile:
    path: /etc/profile.d/999-rke2-path.sh
    line: 'PATH=$PATH:/var/lib/rancher/rke2/bin'
    create: true
    state: present
    mode: '0755'
    owner: root
    group: root

- name: Get latest Calico release data
  ansible.builtin.uri:
    url: https://api.github.com/repos/projectcalico/calico/releases
    return_content: true
    body_format: json
  delegate_to: localhost
  run_once: true
  register: calico_releases
  until: calico_releases.status == 200
  retries: 5
  delay: 2
  changed_when: false
  check_mode: false

- name: Install calicoctl
  ansible.builtin.get_url:
    url: "{{ (calico_releases.json[0].assets | selectattr('name', 'search', 'calicoctl-linux-amd64') | map(attribute='browser_download_url') | first) }}"
    dest: /usr/local/bin/calicoctl
    mode: '0755'
    owner: root
    group: root

- name: Installed iptables
  ansible.builtin.apt:
    name: iptables
    state: present
    update_cache: true
    autoremove: true
  retries: 100
  delay: 5
