apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-external-secrets.yaml
  - helm-bitwarden-sdk.yaml
  - helm-jetstack.yaml
  - helm-ingress-nginx.yaml
  - helm-grafana.yaml
  - helm-longhorn.yaml
