---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-subnet-router
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-subnet-router
  template:
    metadata:
      labels:
        app: tailscale-subnet-router
    spec:
      serviceAccountName: tailscale
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:latest
          env:
            # Podの再起動後もTailscaleのstateを保持するためにk8s secretを指定
            - name: TS_KUBE_SECRET
              value: "tailscale-state"
            # userspace networking modeを無効化し、カーネルモードで動作させる
            - name: TS_USERSPACE
              value: "false"
            # secretからTailscaleのauth keyを読み込む
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
            # 広報するsubnet routes
            - name: TS_ROUTES
              value: "192.168.0.0/24"
            # Tailscaleのホスト名をk8sのノード名に設定
            - name: TS_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Tailscaleのタグを設定
            - name: TS_ADVERTISE_TAGS
              value: "tag:pve,tag:k8s,tag:rke2,tag:subnet_router"
          securityContext:
            # subnet routerとして動作するために特権が必要
            privileged: true
