apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mariadb-secret.yaml
  - mariadb-statefulset.yaml
  - mariadb-service.yaml
  - backup-secret.yaml
  - backup-cronjob.yaml
