apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-credentials
  namespace: infra-db
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: mariadb-credentials
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        # BSM シークレット名: SHARED_MARIADB_ROOT_PASSWORD
        key: SHARED_MARIADB_ROOT_PASSWORD
    - secretKey: EPGSTATION_MYSQL_PASSWORD
      remoteRef:
        # BSM シークレット名: EPGSTATION_MYSQL_PASSWORD
        key: EPGSTATION_MYSQL_PASSWORD
