apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mirakurun-secret.yaml
  - mirakurun-ghcr-pull-secret.yaml
  - mirakurun-configmap.yaml
  - mirakurun-pvc.yaml
  - mirakurun-deployment.yaml
  - mirakurun-service.yaml

images:
  - name: ghcr.io/miutaku/mirakurun
    newTag: 8502d85
