apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mirakurun-secret.yaml
  - mirakurun-configmap.yaml
  - mirakurun-deployment.yaml
  - mirakurun-service.yaml
