apiVersion: v1
kind: Service
metadata:
  name: mirakurun
  namespace: app-mirakurun
spec:
  type: ClusterIP
  selector:
    app: mirakurun
  ports:
    - name: http
      port: 40772
      targetPort: 40772
      protocol: TCP
