apiVersion: v1
kind: ConfigMap
metadata:
  name: mirakurun-config
  namespace: app-mirakurun
data:
  server.yml: |
    logLevel: 2
    maxLogHistory: 1000
    path: /var/run/mirakurun.sock
    address: 0.0.0.0
    port: 40772

  tuners.yml: |
    # PT3 実機確認済み (dmesg): adapter0=ISDB-S, adapter1=ISDB-T, adapter2=ISDB-S, adapter3=ISDB-T
    - name: PT3-S0
      types:
        - BS
        - CS
      dvbDevicePath: /dev/dvb/adapter0/dvr0
      decoder: arib-b25-stream-test
      command: >-
        dvbv5-zap -a 0 -c ./config/dvbconf-for-isdb/conf/dvbv5_channels_isdbs.conf
        -r -P <channel>
      isDisabled: false

    - name: PT3-T0
      types:
        - GR
      dvbDevicePath: /dev/dvb/adapter1/dvr0
      decoder: arib-b25-stream-test
      command: >-
        dvbv5-zap -a 1 -c ./config/dvbconf-for-isdb/conf/dvbv5_channels_isdbt.conf
        -r -P <channel>
      isDisabled: false

    - name: PT3-S1
      types:
        - BS
        - CS
      dvbDevicePath: /dev/dvb/adapter2/dvr0
      decoder: arib-b25-stream-test
      command: >-
        dvbv5-zap -a 2 -c ./config/dvbconf-for-isdb/conf/dvbv5_channels_isdbs.conf
        -r -P <channel>
      isDisabled: false

    - name: PT3-T1
      types:
        - GR
      dvbDevicePath: /dev/dvb/adapter3/dvr0
      decoder: arib-b25-stream-test
      command: >-
        dvbv5-zap -a 3 -c ./config/dvbconf-for-isdb/conf/dvbv5_channels_isdbt.conf
        -r -P <channel>
      isDisabled: false

  channels.yml: |
    # GR
    - name: Ｊ：ＣＯＭテレビ
      type: GR
      channel: '13'
      isDisabled: false
    - name: テレ玉
      type: GR
      channel: '15'
      isDisabled: false
    - name: ｔｖｋ
      type: GR
      channel: '18'
      isDisabled: false
    - name: Ｊ：ＣＯＭチャンネル
      type: GR
      channel: '19'
      isDisabled: false
    - name: ＴＯＫＹＯ　ＭＸ
      type: GR
      channel: '20'
      isDisabled: false
    - name: フジテレビ
      type: GR
      channel: '21'
      isDisabled: false
    - name: ＴＢＳ
      type: GR
      channel: '22'
      isDisabled: false
    - name: テレ東
      type: GR
      channel: '23'
      isDisabled: false
    - name: テレビ朝日
      type: GR
      channel: '24'
      isDisabled: false
    - name: 日テレ
      type: GR
      channel: '25'
      isDisabled: false
    - name: ＮＨＫ　Ｅテレ
      type: GR
      channel: '26'
      isDisabled: false
    - name: ＮＨＫ総合
      type: GR
      channel: '27'
      isDisabled: false
    # BS
    - name: ＢＳ朝日１
      type: BS
      channel: BS01_0
      serviceId: 151
      isDisabled: false
    - name: ＢＳ朝日２
      type: BS
      channel: BS01_0
      serviceId: 152
      isDisabled: false
    - name: ＢＳ朝日３
      type: BS
      channel: BS01_0
      serviceId: 153
      isDisabled: false
    - name: ＢＳ－ＴＢＳ１
      type: BS
      channel: BS01_1
      serviceId: 161
      isDisabled: false
    - name: ＢＳ－ＴＢＳ２
      type: BS
      channel: BS01_1
      serviceId: 162
      isDisabled: false
    - name: ＢＳ－ＴＢＳ３
      type: BS
      channel: BS01_1
      serviceId: 163
      isDisabled: false
    - name: ＢＳ－ＴＢＳ４
      type: BS
      channel: BS01_1
      serviceId: 766
      isDisabled: false
    - name: Ｇガイド
      type: BS
      channel: BS01_1
      serviceId: 768
      isDisabled: false
    - name: ＢＳテレ東１
      type: BS
      channel: BS01_2
      serviceId: 171
      isDisabled: false
    - name: ＢＳテレ東２
      type: BS
      channel: BS01_2
      serviceId: 172
      isDisabled: false
    - name: ＢＳテレ東３
      type: BS
      channel: BS01_2
      serviceId: 173
      isDisabled: false
    - name: 株価情報
      type: BS
      channel: BS01_2
      serviceId: 777
      isDisabled: false
    - name: ＷＯＷＯＷプライム
      type: BS
      channel: BS03_0
      serviceId: 191
      isDisabled: false
    - name: ご案内チャンネル
      type: BS
      channel: BS03_0
      serviceId: 791
      isDisabled: false
    - name: プレミアムナビ
      type: BS
      channel: BS03_0
      serviceId: 792
      isDisabled: false
    - name: ＢＳアニマックス
      type: BS
      channel: BS03_1
      serviceId: 236
      isDisabled: false
    - name: ＢＳ釣りビジョン
      type: BS
      channel: BS03_2
      serviceId: 251
      isDisabled: false
    - name: ＷＯＷＯＷライブ
      type: BS
      channel: BS05_0
      serviceId: 192
      isDisabled: false
    - name: ＷＯＷＯＷシネマ
      type: BS
      channel: BS05_1
      serviceId: 193
      isDisabled: false
    - name: ＷＯＷＯＷライブ２
      type: BS
      channel: BS05_2
      serviceId: 192
      isDisabled: false
    - name: ＢＳ１１イレブン１
      type: BS
      channel: BS09_0
      serviceId: 211
      isDisabled: false
    - name: ＢＳ１１イレブン２
      type: BS
      channel: BS09_1
      serviceId: 211
      isDisabled: false
    - name: ＢＳ１２トゥエルビ
      type: BS
      channel: BS09_2
      serviceId: 222
      isDisabled: false
    - name: ＢＳ日テレ１
      type: BS
      channel: BS13_0
      serviceId: 141
      isDisabled: false
    - name: ＢＳ日テレ２
      type: BS
      channel: BS13_0
      serviceId: 142
      isDisabled: false
    - name: ＢＳ日テレ３
      type: BS
      channel: BS13_0
      serviceId: 143
      isDisabled: false
    - name: ＢＳフジ・１８１
      type: BS
      channel: BS13_1
      serviceId: 181
      isDisabled: false
    - name: ＢＳフジ・１８２
      type: BS
      channel: BS13_1
      serviceId: 182
      isDisabled: false
    - name: ＢＳフジ・１８３
      type: BS
      channel: BS13_1
      serviceId: 183
      isDisabled: false
    - name: 放送大学テレビ１
      type: BS
      channel: BS13_2
      serviceId: 231
      isDisabled: false
    - name: 放送大学テレビ２
      type: BS
      channel: BS13_2
      serviceId: 232
      isDisabled: false
    - name: 放送大学ラジオ
      type: BS
      channel: BS13_2
      serviceId: 531
      isDisabled: false
    - name: ＮＨＫ　ＢＳ１
      type: BS
      channel: BS15_0
      serviceId: 101
      isDisabled: false
    - name: ＮＨＫ　ＢＳ２
      type: BS
      channel: BS15_0
      serviceId: 102
      isDisabled: false
    - name: ＮＨＫデータ１
      type: BS
      channel: BS15_0
      serviceId: 700
      isDisabled: false
    - name: ＮＨＫデータ２
      type: BS
      channel: BS15_0
      serviceId: 701
      isDisabled: false
    - name: ７０７チャンネル
      type: BS
      channel: BS15_0
      serviceId: 707
      isDisabled: false
    - name: Ｄｐａダウンロード
      type: BS
      channel: BS15_0
      serviceId: 929
      isDisabled: false
    - name: ＢＳ１０スターｃｈ１
      type: BS
      channel: BS15_1
      serviceId: 201
      isDisabled: false
    - name: ＢＳ１０スターｃｈ２
      type: BS
      channel: BS15_1
      serviceId: 800
      isDisabled: false
    - name: ＢＳ１０
      type: BS
      channel: BS15_2
      serviceId: 200
      isDisabled: false
    - name: Ｊ　ＳＰＯＲＴＳ　４
      type: BS
      channel: BS19_0
      serviceId: 245
      isDisabled: false
    - name: スカパー！ガイド
      type: BS
      channel: BS19_0
      serviceId: 849
      isDisabled: false
    - name: Ｊ　ＳＰＯＲＴＳ　１
      type: BS
      channel: BS19_1
      serviceId: 242
      isDisabled: false
    - name: Ｊ　ＳＰＯＲＴＳ　２
      type: BS
      channel: BS19_2
      serviceId: 243
      isDisabled: false
    - name: Ｊ　ＳＰＯＲＴＳ　３
      type: BS
      channel: BS19_3
      serviceId: 244
      isDisabled: false
    - name: ＷＯＷＯＷプラス
      type: BS
      channel: BS21_0
      serviceId: 252
      isDisabled: false
    - name: 日本映画専門ｃｈ
      type: BS
      channel: BS21_1
      serviceId: 255
      isDisabled: false
    - name: グリーンチャンネル
      type: BS
      channel: BS21_2
      serviceId: 234
      isDisabled: false
    - name: ディズニーｃｈ１
      type: BS
      channel: BS23_0
      serviceId: 256
      isDisabled: false
    - name: ＢＳよしもと
      type: BS
      channel: BS23_1
      serviceId: 265
      isDisabled: false
    - name: ディズニーｃｈ２
      type: BS
      channel: BS23_2
      serviceId: 256
      isDisabled: false
    - name: ＢＳ松竹東急
      type: BS
      channel: BS23_3
      serviceId: 260
      isDisabled: false
    # CS
    - name: ＴＢＳチャンネル１
      type: CS
      channel: CS2
      serviceId: 296
      isDisabled: false
    - name: テレ朝チャンネル１
      type: CS
      channel: CS2
      serviceId: 298
      isDisabled: false
    - name: テレ朝チャンネル２
      type: CS
      channel: CS2
      serviceId: 299
      isDisabled: false
    - name: ディズニージュニア
      type: CS
      channel: CS2
      serviceId: 339
      isDisabled: false
    - name: スカイＡ
      type: CS
      channel: CS4
      serviceId: 250
      isDisabled: false
    - name: 時代劇専門ｃｈ
      type: CS
      channel: CS4
      serviceId: 292
      isDisabled: false
    - name: エンタメ～テレ
      type: CS
      channel: CS4
      serviceId: 301
      isDisabled: false
    - name: ＭＴＶ
      type: CS
      channel: CS4
      serviceId: 323
      isDisabled: false
    - name: ホームドラマＣＨ
      type: CS
      channel: CS6
      serviceId: 294
      isDisabled: false
    - name: ミュージック・エア
      type: CS
      channel: CS6
      serviceId: 324
      isDisabled: false
    - name: 歌謡ポップス
      type: CS
      channel: CS6
      serviceId: 329
      isDisabled: false
    - name: カートゥーン
      type: CS
      channel: CS6
      serviceId: 331
      isDisabled: false
    - name: ディスカバリー
      type: CS
      channel: CS6
      serviceId: 340
      isDisabled: false
    - name: アニマルプラネット
      type: CS
      channel: CS6
      serviceId: 341
      isDisabled: false
    - name: ＣＮＮｊ
      type: CS
      channel: CS6
      serviceId: 354
      isDisabled: false
    - name: 囲碁・将棋チャンネル
      type: CS
      channel: CS6
      serviceId: 363
      isDisabled: false
    - name: ショップチャンネル
      type: CS
      channel: CS8
      serviceId: 55
      isDisabled: false
    - name: 東映チャンネル
      type: CS
      channel: CS8
      serviceId: 218
      isDisabled: false
    - name: Ｍｎｅｔ
      type: CS
      channel: CS8
      serviceId: 318
      isDisabled: false
    - name: 日テレＮＥＷＳ２４
      type: CS
      channel: CS8
      serviceId: 349
      isDisabled: false
    - name: スカパー！インフォ
      type: CS
      channel: CS10
      serviceId: 101
      isDisabled: false
    - name: 衛星劇場
      type: CS
      channel: CS10
      serviceId: 219
      isDisabled: false
    - name: ＫＢＳ　Ｗｏｒｌｄ
      type: CS
      channel: CS10
      serviceId: 317
      isDisabled: false
    - name: スポーツライブ＋
      type: CS
      channel: CS10
      serviceId: 800
      isDisabled: false
    - name: スカチャン１
      type: CS
      channel: CS10
      serviceId: 801
      isDisabled: false
    - name: ＧＡＯＲＡ
      type: CS
      channel: CS12
      serviceId: 254
      isDisabled: false
    - name: エムオン！
      type: CS
      channel: CS12
      serviceId: 325
      isDisabled: false
    - name: キッズステーション
      type: CS
      channel: CS12
      serviceId: 330
      isDisabled: false
    - name: ナショジオ
      type: CS
      channel: CS12
      serviceId: 343
      isDisabled: false
    - name: ザ・シネマ
      type: CS
      channel: CS14
      serviceId: 227
      isDisabled: false
    - name: ファミリー劇場
      type: CS
      channel: CS14
      serviceId: 293
      isDisabled: false
    - name: スーパー！ドラマＴＶ
      type: CS
      channel: CS14
      serviceId: 310
      isDisabled: false
    - name: ヒストリーチャンネル
      type: CS
      channel: CS14
      serviceId: 342
      isDisabled: false
    - name: ＳＫＹ　ＳＴＡＧＥ
      type: CS
      channel: CS16
      serviceId: 290
      isDisabled: false
    - name: アクションチャンネル
      type: CS
      channel: CS16
      serviceId: 311
      isDisabled: false
    - name: ミステリーチャンネル
      type: CS
      channel: CS16
      serviceId: 316
      isDisabled: false
    - name: スペシャプラス
      type: CS
      channel: CS16
      serviceId: 321
      isDisabled: false
    - name: ＡＴ－Ｘ
      type: CS
      channel: CS16
      serviceId: 333
      isDisabled: false
    - name: ＢＢＣニュース
      type: CS
      channel: CS16
      serviceId: 353
      isDisabled: false
    - name: ムービープラス
      type: CS
      channel: CS18
      serviceId: 240
      isDisabled: false
    - name: ゴルフネットワーク
      type: CS
      channel: CS18
      serviceId: 262
      isDisabled: false
    - name: チャンネル銀河
      type: CS
      channel: CS18
      serviceId: 305
      isDisabled: false
    - name: ＬａＬａＴＶ
      type: CS
      channel: CS18
      serviceId: 314
      isDisabled: false
    - name: フジテレビＯＮＥ
      type: CS
      channel: CS20
      serviceId: 307
      isDisabled: false
    - name: フジテレビＴＷＯ
      type: CS
      channel: CS20
      serviceId: 308
      isDisabled: false
    - name: フジテレビＮＥＸＴ
      type: CS
      channel: CS20
      serviceId: 309
      isDisabled: false
    - name: スペースシャワーＴＶ
      type: CS
      channel: CS20
      serviceId: 322
      isDisabled: false
    - name: ＱＶＣ
      type: CS
      channel: CS22
      serviceId: 161
      isDisabled: false
    - name: ＴＢＳチャンネル２
      type: CS
      channel: CS22
      serviceId: 297
      isDisabled: false
    - name: Ｄｌｉｆｅ
      type: CS
      channel: CS22
      serviceId: 312
      isDisabled: false
    - name: ＴＢＳ　ＮＥＷＳ
      type: CS
      channel: CS22
      serviceId: 351
      isDisabled: false
    - name: 映画・ｃｈＮＥＣＯ
      type: CS
      channel: CS24
      serviceId: 223
      isDisabled: false
    - name: 日テレジータス
      type: CS
      channel: CS24
      serviceId: 257
      isDisabled: false
    - name: ＭＯＮＤＯ　ＴＶ
      type: CS
      channel: CS24
      serviceId: 295
      isDisabled: false
    - name: 日テレプラス
      type: CS
      channel: CS24
      serviceId: 300
      isDisabled: false
