apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mirakurun-bcas-keys
  namespace: app-mirakurun
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: mirakurun-bcas-keys
    creationPolicy: Owner
  data:
    - secretKey: bcas_keys
      remoteRef:
        # BSM シークレット名: MIRAKURUN_BCAS_KEYS
        # 値: bcas_keys ファイルの内容をそのままペースト
        key: MIRAKURUN_BCAS_KEYS
