apiVersion: v1
kind: Namespace
metadata:
  name: talos-poc-metallb
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-nginx
  namespace: talos-poc-metallb
data:
  default.conf: |
    server {
      listen 8080;
      location / {
        return 200 "talos-poc-metallb-ok\n";
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: talos-poc-metallb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: nginx:1.29.1-alpine
          command:
            - nginx
          args:
            - -g
            - daemon off;
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 101
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
      volumes:
        - name: config
          configMap:
            name: echo-nginx
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: talos-poc-metallb
  annotations:
    metallb.io/loadBalancerIPs: 192.168.20.228
spec:
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  selector:
    app: echo
  ports:
    - name: http
      port: 80
      targetPort: http
