apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - nextcloud-secret.yaml
  - ghcr-pull-secret.yaml
  - nextcloud-configmap.yaml
  - redis.yaml
  - nextcloud-deployment.yaml
  - nextcloud-service.yaml
