apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: gptwol-computers
    namespace: app-gptwol
    files:
      - computers.txt=./appdata/db/computers.txt
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
