apiVersion: v1
kind: Service
metadata:
  name: unifi-unifi-os-server-discovery-v1
  namespace: unifi
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.20.202"
    metallb.universe.tf/allow-shared-ip: "unifi"
  labels:
    app.kubernetes.io/instance: unifi
    app.kubernetes.io/name: unifi-os-server
    unifi-os-server.io/port: discovery-v1
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: discovery-v1
      port: 10001
      protocol: UDP
      targetPort: 10001
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: unifi
    app.kubernetes.io/name: unifi-os-server
