systemIp: "192.168.20.202"

service:
  type: LoadBalancer
  loadBalancerIP: "192.168.20.202"
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.20.202"
    metallb.universe.tf/allow-shared-ip: "unifi"

persistence:
  data:
    storageClass: local-path
    size: 20Gi
  mongo:
    storageClass: local-path
    size: 10Gi

nodeSelector:
  unifi: "true"

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: "4"
    memory: 6Gi
