systemIp: "192.168.0.202"

service:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.20.202"
    metallb.universe.tf/allow-shared-ip: "unifi"

persistence:
  data:
    storageClass: local-path
    size: 20Gi
  mongo:
    storageClass: local-path
    size: 10Gi

nodeSelector:
  unifi: "true"

resources:
  requests:
    cpu: 500m
    memory: 4Gi
  limits:
    cpu: "4"
    memory: 6Gi

probes:
  liveness:
    enabled: true
    exec:
      command:
        - curl
        - -k
        - -L
        - -m
        - "5"
        - -fsS
        - http://127.0.0.1/api/ping
    initialDelaySeconds: 180
    periodSeconds: 60
    timeoutSeconds: 10
    failureThreshold: 5
    successThreshold: 1
  readiness:
    enabled: true
    exec:
      command:
        - curl
        - -k
        - -L
        - -m
        - "5"
        - -fsS
        - http://127.0.0.1/api/ping
    initialDelaySeconds: 60
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 10
    successThreshold: 1
