apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
data:
  previews.config.php: |
    <?php
    $CONFIG = [
      'enabledPreviewProviders' => [
        'OC\Preview\PNG', 'OC\Preview\JPEG', 'OC\Preview\GIF',
        'OC\Preview\BMP', 'OC\Preview\WebP', 'OC\Preview\XBitmap',
        'OC\Preview\MarkDown', 'OC\Preview\TXT',
        'OC\Preview\OpenDocument', 'OC\Preview\Krita', 'OC\Preview\Movie',
      ],
    ];
  mimetypemapping.json: |
    {"m2ts": ["video/mp2t"], "mts": ["video/mp2t"]}
