apiVersion: v1
kind: Pod
metadata:
  name: nextcloud-html-copy-receiver
  namespace: app-nextcloud
spec:
  restartPolicy: Never
  containers:
    - name: receiver
      image: ghcr.io/miutaku/nextcloud-ffmpeg:latest
      command: [sh, -ec, sleep 86400]
      volumeMounts:
        - name: html
          mountPath: /target
  volumes:
    - name: html
      persistentVolumeClaim:
        claimName: nextcloud-html-pvc
