apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-html-pvc
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-green-recorded-readonly-pv
spec:
  capacity:
    storage: 200Gi
  accessModes: [ReadOnlyMany]
  nfs:
    server: 192.168.20.192
    path: /mnt/raid1_case/recorded
    readOnly: true
  mountOptions: [nfsvers=4.1, hard, timeo=600, retrans=3, ro]
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nas-recorded-pvc
spec:
  accessModes: [ReadOnlyMany]
  resources:
    requests:
      storage: 200Gi
  volumeName: nextcloud-green-recorded-readonly-pv
  storageClassName: ""
