all:
  children:
    loockit_hosts:
      hosts:
        pve-x570:
          loockit_ct_id: 12902
          loockit_address: 192.168.20.133
          loockit_identity: loockit-x570
        pve-b550m:
          loockit_ct_id: 12903
          loockit_address: 192.168.20.134
          loockit_identity: loockit-b550m
  hosts:
    pve-x570:
      ansible_host: 192.168.0.115
      ansible_user: root
      ansible_ssh_common_args: -o StrictHostKeyChecking=accept-new
    pve-b550m:
      ansible_host: 192.168.0.119
      ansible_user: root
      ansible_ssh_common_args: -o StrictHostKeyChecking=accept-new
