dev_user: miutaku
dev_group: miutaku
dev_home: /home/miutaku

dev_apt_packages:
  - ansible-core
  - apt-transport-https
  - azure-cli
  - ca-certificates
  - containerd.io
  - curl
  - docker-buildx-plugin
  - docker-ce
  - docker-ce-cli
  - docker-ce-rootless-extras
  - docker-compose-plugin
  - docker-model-plugin
  - dotnet-sdk-10.0
  - ffmpeg
  - fonts-freefont-ttf
  - fonts-ipafont-gothic
  - fonts-liberation
  - fonts-noto-cjk
  - fonts-noto-color-emoji
  - fonts-tlwg-loma-otf
  - fonts-unifont
  - fonts-wqy-zenhei
  - gcc-mingw-w64-x86-64
  - gh
  - gnupg
  - golang
  - google-android-platform-tools-installer
  - google-chrome-stable
  - jq
  - kubectl
  - libasound2t64
  - libatk-bridge2.0-0t64
  - libatk1.0-0t64
  - libatspi2.0-0t64
  - libcairo2
  - libcups2t64
  - libdbus-1-3
  - libdrm2
  - libfontconfig1
  - libfreetype6
  - libgbm1
  - libgl1-mesa-dev
  - libglib2.0-0t64
  - libnspr4
  - libnss3
  - libpango-1.0-0
  - libx11-6
  - libxcb1
  - libxcomposite1
  - libxdamage1
  - libxext6
  - libxfixes3
  - libxkbcommon0
  - libxrandr2
  - lsb-release
  - ngrok
  - nodejs
  - npm
  - openssh-server
  - python3-full
  - python3-pip
  - python3-venv
  - python3-xyzservices
  - ripgrep
  - ruby
  - software-properties-common
  - terraform
  - unzip
  - unattended-upgrades
  - usb-modeswitch
  - xfonts-cyrillic
  - xfonts-scalable
  - xorg-dev
  - xvfb

talosctl_version: "1.14.1"
talosctl_sha256: 7233ece94c94296a033a6ddb5efe0baf508a94c71de7e6c7b286500705924208

packer_version: "1.11.2"
packer_archive_sha256: ced13efc257d0255932d14b8ae8f38863265133739a007c430cae106afcfc45a

d2_version: "0.7.1"
d2_archive_sha256: eb172adf59f38d1e5a70ab177591356754ffaf9bebb84e0ca8b767dfb421dad7

uv_version: "0.11.29"
uv_archive_sha256: 04f8b82f5d47f0512dcd32c67a4a6f16a0ea27c81537c338fd0ad6b23cebe829

bws_version: "2.0.0"
bws_archive_sha256: a8340ce01da609200441f2eca0e591173e124f012c88a16afda574279c052013

kubectx_version: "0.11.0"
kubectx_archive_sha256: 08e031c54fbffb3f100e904e4eae94bba2730fedf4869921fda79e4d7a8f5d4c
kubectx_binary_sha256: b24e6a157ddb824473349ec09e2b7487b6faeb3a9a3ca71a1615e06520b74aa6
kubens_archive_sha256: 326c021c7b35468ed9a187b361198d0f22ae32828139c65eb6670c0d8301cc09
kubens_binary_sha256: 91ca1b0294b4ba5e842f378a9f59c380800314d0f5adad74b8e5b86df968669f

pipenv_version: "2026.6.1"
virtualenv_version: "21.3.1"
oci_cli_version: "3.81.1"
mermaid_cli_version: "11.15.0"
bitwarden_cli_version: "2026.5.0"

required_bsm_secrets:
  - OCI_TENANCY_OCID
  - OCI_USER_OCID
  - OCI_FINGERPRINT
  - OCI_REGION
  - OCI_PRIVATE_KEY
  - PRD_OCI_TENANCY_OCID
  - PRD_OCI_USER_OCID
  - PRD_OCI_FINGERPRINT
  - PRD_OCI_REGION
  - PRD_OCI_API_KEY_PEM
