apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coupon-images
  namespace: app-coupon-manager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-data-protection-keys
  namespace: app-coupon-manager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
