apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coupon-manager-secrets
  namespace: app-coupon-manager
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: coupon-manager-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: COUPON_MANAGER_POSTGRES_PASSWORD
    - secretKey: AI_API_KEY
      remoteRef:
        key: COUPON_MANAGER_AI_API_KEY
