apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oci-actions-runner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/miutaku/my-infra.git
    targetRevision: main
    path: k8s/oci/apps/actions-runner
  destination:
    server: https://kubernetes.default.svc
    namespace: actions-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
