apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oci-arc-runners-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/miutaku/my-infra.git
    targetRevision: main
    path: k8s/oci/arc-runners
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
