apiVersion: v1
kind: ConfigMap
metadata:
  name: tnlastation-config
  namespace: app-tnlastation
data:
  config.yml: |
    port: 8080
    clientSocketioPort: 443
    mirakurunPath: http://mirakurun.app-mirakurun.svc.cluster.local:40772

    dbtype: postgres

    needToReplaceEnclosingCharacters: true
    epgUpdateIntervalTime: 10
    conflictPriority: 1
    recPriority: 2
    streamingPriority: 0

    isEnabledDropCheck: true
    recordedFormat: '%TITLE%-%YEAR%年%MONTH%月%DAY%日%HOUR%時%MIN%分%SEC%秒'
    recordedFileExtension: .m2ts
    recorded:
      - name: recorded
        path: /recorded
        limitThreshold: 10000
        action: remove

    thumbnail: /var/lib/tnlastation/thumbnails
    thumbnailSize: 480x270
    thumbnailPosition: 10
    dropLog: /var/lib/tnlastation/drop
    streamFilePath: /var/lib/tnlastation/streamfiles
    uploadTempDir: /var/lib/tnlastation/upload

    ffmpeg: /usr/bin/ffmpeg
    ffprobe: /usr/bin/ffprobe
    encodeProcessNum: 4
    concurrentEncodeNum: 4
    encode:
      - name: H.264
        cmd: >-
          %FFMPEG% -hide_banner -nostats -i %INPUT%
          -map 0:v:0 -map 0:a:0 -ignore_unknown -sn -dn
          -c:v libx264 -preset veryfast -profile:v high -crf 23 -vf yadif
          -c:a aac -ar 48000 -b:a 192k -ac 2
          -movflags +faststart -y %OUTPUT%
        suffix: -avc.mp4
        rate: 4.0
      - name: H.265
        cmd: >-
          %FFMPEG% -hide_banner -nostats -i %INPUT%
          -map 0:v:0 -map 0:a:0 -ignore_unknown -sn -dn
          -c:v libx265 -preset veryfast -crf 28 -vf yadif
          -c:a aac -ar 48000 -b:a 192k -ac 2
          -movflags +faststart -y %OUTPUT%
        suffix: -hevc.mp4
        rate: 8.0

    stream:
      live:
        ts:
          m2ts:
            - name: 無変換
            - name: 1080p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 0
                -c:a aac -ar 48000 -b:a 192k -ac 2
                -c:v libx264 -vf yadif,scale=-2:1080 -b:v 5000k -preset veryfast
                -y -f mpegts pipe:1
            - name: 720p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 0
                -c:a aac -ar 48000 -b:a 192k -ac 2
                -c:v libx264 -vf yadif,scale=-2:720 -b:v 3000k -preset veryfast
                -y -f mpegts pipe:1
            - name: 480p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 0
                -c:a aac -ar 48000 -b:a 128k -ac 2
                -c:v libx264 -vf yadif,scale=-2:480 -b:v 1500k -preset veryfast
                -y -f mpegts pipe:1
          m2tsll:
            - name: 1080p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -f mpegts -analyzeduration 500000 -i pipe:0
                -map 0 -c:s copy -c:d copy -ignore_unknown -fflags nobuffer -flags low_delay
                -max_delay 250000 -max_interleave_delta 1 -threads 0
                -c:a aac -ar 48000 -b:a 192k -ac 2
                -c:v libx264 -flags +cgop -vf yadif,scale=-2:1080 -b:v 5000k -preset veryfast
                -y -f mpegts pipe:1
            - name: 720p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -f mpegts -analyzeduration 500000 -i pipe:0
                -map 0 -c:s copy -c:d copy -ignore_unknown -fflags nobuffer -flags low_delay
                -max_delay 250000 -max_interleave_delta 1 -threads 0
                -c:a aac -ar 48000 -b:a 192k -ac 2
                -c:v libx264 -flags +cgop -vf yadif,scale=-2:720 -b:v 3000k -preset veryfast
                -y -f mpegts pipe:1
            - name: 480p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -f mpegts -analyzeduration 500000 -i pipe:0
                -map 0 -c:s copy -c:d copy -ignore_unknown -fflags nobuffer -flags low_delay
                -max_delay 250000 -max_interleave_delta 1 -threads 0
                -c:a aac -ar 48000 -b:a 128k -ac 2
                -c:v libx264 -flags +cgop -vf yadif,scale=-2:480 -b:v 1500k -preset veryfast
                -y -f mpegts pipe:1
          webm:
            - name: 1080p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 3
                -c:a libvorbis -ar 48000 -b:a 192k -ac 2
                -c:v libvpx-vp9 -vf yadif,scale=-2:1080 -b:v 5000k
                -deadline realtime -speed 4 -cpu-used -8 -y -f webm pipe:1
            - name: 720p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 3
                -c:a libvorbis -ar 48000 -b:a 192k -ac 2
                -c:v libvpx-vp9 -vf yadif,scale=-2:720 -b:v 3000k
                -deadline realtime -speed 4 -cpu-used -8 -y -f webm pipe:1
            - name: 480p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 2
                -c:a libvorbis -ar 48000 -b:a 128k -ac 2
                -c:v libvpx-vp9 -vf yadif,scale=-2:480 -b:v 1500k
                -deadline realtime -speed 4 -cpu-used -8 -y -f webm pipe:1
          mp4:
            - name: 1080p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 0
                -c:a aac -ar 48000 -b:a 192k -ac 2
                -c:v libx264 -vf yadif,scale=-2:1080 -b:v 5000k -profile:v baseline -preset veryfast
                -tune fastdecode,zerolatency
                -movflags frag_keyframe+empty_moov+faststart+default_base_moof
                -y -f mp4 pipe:1
            - name: 720p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 0
                -c:a aac -ar 48000 -b:a 192k -ac 2
                -c:v libx264 -vf yadif,scale=-2:720 -b:v 3000k -profile:v baseline -preset veryfast
                -tune fastdecode,zerolatency
                -movflags frag_keyframe+empty_moov+faststart+default_base_moof
                -y -f mp4 pipe:1
            - name: 480p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 0
                -c:a aac -ar 48000 -b:a 128k -ac 2
                -c:v libx264 -vf yadif,scale=-2:480 -b:v 1500k -profile:v baseline -preset veryfast
                -tune fastdecode,zerolatency
                -movflags frag_keyframe+empty_moov+faststart+default_base_moof
                -y -f mp4 pipe:1
          hls:
            - name: 1080p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -map 0 -threads 0 -ignore_unknown
                -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 17 -hls_allow_cache 1
                -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts
                -hls_flags delete_segments
                -c:a aac -ar 48000 -b:a 192k -ac 2
                -c:v libx264 -vf yadif,scale=-2:1080 -b:v 5000k -preset veryfast
                -flags +loop-global_header %OUTPUT%
            - name: 720p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -map 0 -threads 0 -ignore_unknown
                -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 17 -hls_allow_cache 1
                -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts
                -hls_flags delete_segments
                -c:a aac -ar 48000 -b:a 192k -ac 2
                -c:v libx264 -vf yadif,scale=-2:720 -b:v 3000k -preset veryfast
                -flags +loop-global_header %OUTPUT%
            - name: 480p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -map 0 -threads 0 -ignore_unknown
                -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 17 -hls_allow_cache 1
                -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts
                -hls_flags delete_segments
                -c:a aac -ar 48000 -b:a 128k -ac 2
                -c:v libx264 -vf yadif,scale=-2:480 -b:v 1500k -preset veryfast
                -flags +loop-global_header %OUTPUT%
      recorded:
        ts:
          webm:
            - name: 1080p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 3
                -c:a libvorbis -ar 48000 -b:a 192k -ac 2
                -c:v libvpx-vp9 -vf yadif,scale=-2:1080 -b:v 5000k
                -deadline realtime -speed 4 -cpu-used -8 -y -f webm pipe:1
            - name: 720p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 3
                -c:a libvorbis -ar 48000 -b:a 192k -ac 2
                -c:v libvpx-vp9 -vf yadif,scale=-2:720 -b:v 3000k
                -deadline realtime -speed 4 -cpu-used -8 -y -f webm pipe:1
            - name: 480p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 3
                -c:a libvorbis -ar 48000 -b:a 128k -ac 2
                -c:v libvpx-vp9 -vf yadif,scale=-2:480 -b:v 1500k
                -deadline realtime -speed 4 -cpu-used -8 -y -f webm pipe:1
          mp4:
            - name: 1080p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 0
                -c:a aac -ar 48000 -b:a 192k -ac 2
                -c:v libx264 -vf yadif,scale=-2:1080 -b:v 5000k -profile:v baseline -preset veryfast
                -tune fastdecode,zerolatency
                -movflags frag_keyframe+empty_moov+faststart+default_base_moof
                -y -f mp4 pipe:1
            - name: 720p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 0
                -c:a aac -ar 48000 -b:a 192k -ac 2
                -c:v libx264 -vf yadif,scale=-2:720 -b:v 3000k -profile:v baseline -preset veryfast
                -tune fastdecode,zerolatency
                -movflags frag_keyframe+empty_moov+faststart+default_base_moof
                -y -f mp4 pipe:1
            - name: 480p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 0
                -c:a aac -ar 48000 -b:a 128k -ac 2
                -c:v libx264 -vf yadif,scale=-2:480 -b:v 1500k -profile:v baseline -preset veryfast
                -tune fastdecode,zerolatency
                -movflags frag_keyframe+empty_moov+faststart+default_base_moof
                -y -f mp4 pipe:1
          hls:
            - name: 1080p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -map 0 -threads 0 -ignore_unknown
                -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1
                -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts
                -hls_flags delete_segments
                -c:a aac -ar 48000 -b:a 192k -ac 2
                -c:v libx264 -vf yadif,scale=-2:1080 -b:v 5000k -preset veryfast
                -flags +loop-global_header %OUTPUT%
            - name: 720p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -map 0 -threads 0 -ignore_unknown
                -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1
                -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts
                -hls_flags delete_segments
                -c:a aac -ar 48000 -b:a 192k -ac 2
                -c:v libx264 -vf yadif,scale=-2:720 -b:v 3000k -preset veryfast
                -flags +loop-global_header %OUTPUT%
            - name: 480p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -i pipe:0 -sn -map 0 -threads 0 -ignore_unknown
                -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1
                -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts
                -hls_flags delete_segments
                -c:a aac -ar 48000 -b:a 128k -ac 2
                -c:v libx264 -vf yadif,scale=-2:480 -b:v 1500k -preset veryfast
                -flags +loop-global_header %OUTPUT%
        encoded:
          webm:
            - name: 1080p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 3
                -c:a libvorbis -ar 48000 -b:a 192k -ac 2
                -c:v libvpx-vp9 -vf scale=-2:1080 -b:v 5000k
                -deadline realtime -speed 4 -cpu-used -8 -y -f webm pipe:1
            - name: 720p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 3
                -c:a libvorbis -ar 48000 -b:a 192k -ac 2
                -c:v libvpx-vp9 -vf scale=-2:720 -b:v 3000k
                -deadline realtime -speed 4 -cpu-used -8 -y -f webm pipe:1
            - name: 480p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 3
                -c:a libvorbis -ar 48000 -b:a 128k -ac 2
                -c:v libvpx-vp9 -vf scale=-2:480 -b:v 1500k
                -deadline realtime -speed 4 -cpu-used -8 -y -f webm pipe:1
          mp4:
            - name: 1080p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 0
                -c:a aac -ar 48000 -b:a 192k -ac 2
                -c:v libx264 -vf scale=-2:1080 -b:v 5000k -profile:v baseline -preset veryfast
                -tune fastdecode,zerolatency
                -movflags frag_keyframe+empty_moov+faststart+default_base_moof
                -y -f mp4 pipe:1
            - name: 720p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 0
                -c:a aac -ar 48000 -b:a 192k -ac 2
                -c:v libx264 -vf scale=-2:720 -b:v 3000k -profile:v baseline -preset veryfast
                -tune fastdecode,zerolatency
                -movflags frag_keyframe+empty_moov+faststart+default_base_moof
                -y -f mp4 pipe:1
            - name: 480p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 0
                -c:a aac -ar 48000 -b:a 128k -ac 2
                -c:v libx264 -vf scale=-2:480 -b:v 1500k -profile:v baseline -preset veryfast
                -tune fastdecode,zerolatency
                -movflags frag_keyframe+empty_moov+faststart+default_base_moof
                -y -f mp4 pipe:1
          hls:
            - name: 1080p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 0 -ignore_unknown
                -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1
                -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts
                -hls_flags delete_segments
                -c:a aac -ar 48000 -b:a 192k -ac 2
                -c:v libx264 -vf scale=-2:1080 -b:v 5000k -preset veryfast
                -flags +loop-global_header %OUTPUT%
            - name: 720p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 0 -ignore_unknown
                -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1
                -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts
                -hls_flags delete_segments
                -c:a aac -ar 48000 -b:a 192k -ac 2
                -c:v libx264 -vf scale=-2:720 -b:v 3000k -preset veryfast
                -flags +loop-global_header %OUTPUT%
            - name: 480p
              cmd: >-
                %FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 0 -ignore_unknown
                -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1
                -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts
                -hls_flags delete_segments
                -c:a aac -ar 48000 -b:a 128k -ac 2
                -c:v libx264 -vf scale=-2:480 -b:v 1500k -preset veryfast
                -flags +loop-global_header %OUTPUT%

  nginx.conf: |
    pid /tmp/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        sendfile on;
        server_tokens off;
        proxy_read_timeout 1h;
        proxy_send_timeout 1h;
        client_max_body_size 0;

        upstream backend {
            server backend:8080;
        }

        upstream frontend {
            server frontend:3000;
        }

        server {
            listen 8080;
            server_name _;
            proxy_http_version 1.1;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $http_upgrade;

            location /api/ {
                proxy_pass http://backend;
                proxy_buffering off;
            }

            location /api-docs {
                proxy_pass http://backend;
            }

            location /streamfiles/ {
                proxy_pass http://backend;
                proxy_buffering off;
            }

            location /socket.io/ {
                proxy_pass http://backend;
                proxy_buffering off;
            }

            location / {
                proxy_pass http://frontend;
            }
        }
    }
