apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app-tnlastation
spec:
  type: ClusterIP
  selector:
    app: tnlastation-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-tnlastation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tnlastation-frontend
  template:
    metadata:
      labels:
        app: tnlastation-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/miutaku/tnlastation-frontend:1.0.1
          env:
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_TNLA_API_BASE
              value: /api
            - name: TZ
              value: Asia/Tokyo
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30

