apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - pvc.yaml
  - ffmpeg-worker-encode.yaml
  - ffmpeg-worker-encode-arm64.yaml
  - ffmpeg-worker-streaming.yaml
  - backend.yaml
  - frontend.yaml
  - mediamtx.yaml
  - gateway.yaml
