apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tnlastation-secrets
  namespace: app-tnlastation
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: tnlastation-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_PASSWORD: "{{ .postgres_password }}"
        POSTGRES_CONNECTION_STRING: >-
          Host=postgres.infra-db.svc.cluster.local;Port=5432;Database=tnlastation;Username=tnlastation;Password={{ .postgres_password }}
  data:
    - secretKey: postgres_password
      remoteRef:
        # BSM シークレット名: TNLASTATION_POSTGRES_PASSWORD
        key: TNLASTATION_POSTGRES_PASSWORD
