apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tinytuya-device
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: tinytuya-device
    creationPolicy: Owner
  data:
    - secretKey: device-id
      remoteRef:
        key: TINYTUYA_TUYA16A_UPS_DEVICE_ID
    - secretKey: local-key
      remoteRef:
        key: TINYTUYA_TUYA16A_UPS_LOCAL_KEY
    - secretKey: desk-device-id
      remoteRef:
        key: TINYTUYA_TUYA16A_DESK_DEVICE_ID
    - secretKey: desk-local-key
      remoteRef:
        key: TINYTUYA_TUYA16A_DESK_LOCAL_KEY
    - secretKey: refrigerator-device-id
      remoteRef:
        key: TINYTUYA_TUYA16A_REFRIGERATOR_DEVICE_ID
    - secretKey: refrigerator-local-key
      remoteRef:
        key: TINYTUYA_TUYA16A_REFRIGERATOR_LOCAL_KEY
    - secretKey: washing-machine-device-id
      remoteRef:
        key: TINYTUYA_TUYA16A_WASHING_MACHINE_DEVICE_ID
    - secretKey: washing-machine-local-key
      remoteRef:
        key: TINYTUYA_TUYA16A_WASHING_MACHINE_LOCAL_KEY
    - secretKey: bedside-device-id
      remoteRef:
        key: TINYTUYA_TUYA16A_BEDSIDE_DEVICE_ID
    - secretKey: bedside-local-key
      remoteRef:
        key: TINYTUYA_TUYA16A_BEDSIDE_LOCAL_KEY
    - secretKey: entrance-device-id
      remoteRef:
        key: TINYTUYA_TUYA16A_ENTRANCE_DEVICE_ID
    - secretKey: entrance-local-key
      remoteRef:
        key: TINYTUYA_TUYA16A_ENTRANCE_LOCAL_KEY
