apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tinytuya-device
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: tinytuya-device
    creationPolicy: Owner
  data:
    - secretKey: device-id
      remoteRef:
        key: TINYTUYA_TUYA16A_DEVICE_ID
    - secretKey: local-key
      remoteRef:
        key: TINYTUYA_TUYA16A_LOCAL_KEY
