apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden
spec:
  provider:
    bitwarden:
      auth:
        secretRef:
          credentials:
            # Step 3 で kubectl create secret した Bootstrap Secret を参照する
            name: bitwarden-access-token
            namespace: external-secrets
            key: token
      # bitwarden-sdk-server Service (external-secrets namespace)
      bitwardenServerSDKURL: "http://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998"
      organizationID: "a2677219-8826-443c-a97f-b2e900a2db1f"
      projectID: "ddca6f59-7be5-4e9a-ad28-b43a007dce9e"
