apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tfc-agent-credentials
  namespace: tfc-agent
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: tfc-agent-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        # BSM シークレット名: TFC_HOME_AGENT_TOKEN
        key: TFC_HOME_AGENT_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: name
      remoteRef:
        # BSM シークレット名: TFC_HOME_AGENT_NAME
        key: TFC_HOME_AGENT_NAME
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
