apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: my-infra
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/miutaku/my-infra.git
  ref:
    branch: main
