apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oci-external-secrets-config
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: oci-external-secrets
  sourceRef:
    kind: GitRepository
    name: my-infra
  path: ./k8s/oci/infrastructure/external-secrets-config
  prune: true
  timeout: 5m
  healthChecks:
    - apiVersion: external-secrets.io/v1beta1
      kind: ClusterSecretStore
      name: bitwarden
