apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitrepository.yaml
  - kustomization-sources.yaml
  - kustomization-external-secrets.yaml
  - kustomization-external-secrets-config.yaml
  - kustomization-cert-manager.yaml
  - kustomization-cert-manager-config.yaml
  - kustomization-ingress-nginx.yaml
  - kustomization-longhorn.yaml
  - kustomization-apps.yaml
  - kustomization-encode-worker.yaml
