unauthorized_user:
  url_map:
    - src_paths: ['/select/.*']
      url_prefix:
        - 'http://127.0.0.1:19428/'
        - '%{PEER_LOGS_URL}'
      load_balancing_policy: first_available
      retry_status_codes: [500, 502, 503, 504, 520, 521, 522, 523, 524, 525, 526, 530]
      headers:
        - 'CF-Access-Client-Id: %{CF_ACCESS_CLIENT_ID}'
        - 'CF-Access-Client-Secret: %{CF_ACCESS_CLIENT_SECRET}'
        - 'User-Agent: ReVenter-Observability/1.0'
