apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden
spec:
  provider:
    bitwarden:
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            namespace: external-secrets
            key: token
      bitwardenServerSDKURL: "http://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998"
      organizationID: "CHANGE_ME"
      projectID: "CHANGE_ME"
