apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-pdc-credentials
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: grafana-pdc-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: GRAFANA_PDC_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: hosted-grafana-id
      remoteRef:
        key: GRAFANA_PDC_HOSTED_GRAFANA_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: cluster
      remoteRef:
        key: GRAFANA_PDC_CLUSTER
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
