apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-cloud-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: grafana-cloud-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: metrics-url
      remoteRef:
        key: GRAFANA_CLOUD_METRICS_URL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: metrics-username
      remoteRef:
        key: GRAFANA_CLOUD_METRICS_USERNAME
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: metrics-password
      remoteRef:
        key: GRAFANA_CLOUD_METRICS_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
