apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-cloud-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: grafana-cloud-credentials
    creationPolicy: Owner
  data:
    - secretKey: metrics-url
      remoteRef:
        key: GRAFANA_CLOUD_METRICS_URL
    - secretKey: metrics-username
      remoteRef:
        key: GRAFANA_CLOUD_METRICS_USERNAME
    - secretKey: metrics-password
      remoteRef:
        key: GRAFANA_CLOUD_METRICS_PASSWORD
