apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: magic-mirror-config
  namespace: app-magic-mirror
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: magic-mirror-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.js: |
          let config = {
            address: "0.0.0.0",
            port: 8080,
            basePath: "/",
            ipWhitelist: [],
            useHttps: false,
            httpsPrivateKey: "",
            httpsCertificate: "",

            language: "ja",
            locale: "ja-JP",
            logLevel: ["INFO", "LOG", "WARN", "ERROR"],
            timeFormat: 24,
            units: "metric",

            modules: [
              { module: "alert" },
              { module: "updatenotification", position: "top_bar" },
              {
                module: "clock",
                position: "top_left",
                config: {
                  timeFormat: 24,
                  dateFormat: "YYYY/MM/DD dddd",
                },
              },
              {
                module: "weather",
                position: "top_left",
                config: {
                  weatherProvider: "openweathermap",
                  type: "current",
                  weatherEndpoint: "/weather",
                  showHumidity: true,
                  showFeelsLike: true,
                  units: "metric",
                  degreeLabel: true,
                  lang: "ja",
                  location: "Tokyo",
                  locationID: "1850144",
                  apiKey: "{{ .ow_api_key }}",
                },
              },
              {
                module: "calendar",
                header: "Next event is...",
                position: "top_left",
                config: {
                  fetchInterval: 100000,
                  displaySymbol: false,
                  maxTitleLength: 10,
                  maximumEntries: 3,
                  timeClass: true,
                  fade: true,
                  fadePoint: 0.15,
                  tableClass: "small",
                  timeFormat: "absolute",
                  flipDateHeaderTitle: true,
                  limitDaysNeverSkip: true,
                  calendars: [{ url: "{{ .calendar_url }}" }],
                },
              },
              {
                module: "calendar",
                header: "EVENT LIST",
                position: "top_right",
                config: {
                  fetchInterval: 100000,
                  displaySymbol: false,
                  maxTitleLength: 50,
                  maximumEntries: 19,
                  timeClass: true,
                  fade: false,
                  tableClass: "xsmall",
                  timeFormat: "absolute",
                  flipDateHeaderTitle: true,
                  limitDaysNeverSkip: true,
                  calendars: [{ url: "{{ .calendar_url }}" }],
                },
              },
            ],
          };

          if (typeof module !== "undefined") { module.exports = config; }
  data:
    - secretKey: ow_api_key
      remoteRef:
        # BSM シークレット名: MM_OW_API_KEY
        key: MM_OW_API_KEY
    - secretKey: calendar_url
      remoteRef:
        # BSM シークレット名: MM_CALENDAR_URL
        key: MM_CALENDAR_URL
