apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: reventer-tfc-agent-credentials
  namespace: reventer-tfc-agent
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: reventer-tfc-agent-credentials
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: TFC_REVENTER_AGENT_TOKEN
    - secretKey: name
      remoteRef:
        key: TFC_REVENTER_AGENT_NAME
