apiVersion: v1
kind: ConfigMap
metadata:
  name: loockit-config
  namespace: app-loockit
data:
  config.toml: |
    [grpc]
    host = "0.0.0.0"
    port = 50051

    [matter]
    enabled = false

    [rest]
    enabled = true
    host = "0.0.0.0"
    port = 8080

    [mqtt]
    enabled = false

    [history]
    enabled = false

    cloud_fallback = false

    [[devices]]
    id = "desk-bot"
    model = "SESAMEBOT1"
    ble_address = "E0:5B:CF:D3:A3:60"

