apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loockit-keys
  namespace: app-loockit
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: loockit-keys
    creationPolicy: Owner
  data:
    - secretKey: LOOCKIT_INTERCOM_BOT_SECRET_KEY
      remoteRef:
        key: LOOCKIT_INTERCOM_BOT_SECRET_KEY
    - secretKey: LOOCKIT_INTERCOM_BOT_PUBLIC_KEY
      remoteRef:
        key: LOOCKIT_INTERCOM_BOT_PUBLIC_KEY
