apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tnlastation-recorded-backup-credentials
  namespace: infra-backup
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: tnlastation-recorded-backup-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: IDRIVE_ACCESS_KEY_ID
      remoteRef:
        key: TV_REC_IDRIVE_S3_ACCESS_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: IDRIVE_SECRET_ACCESS_KEY
      remoteRef:
        key: TV_REC_IDRIVE_S3_SECRET_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: TNLASTATION_POSTGRES_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: NOTIFY_WEBHOOK
      remoteRef:
        key: MARIADB_BACKUP_NOTIFY_WEBHOOK
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: CRITICAL_WEBHOOK
      remoteRef:
        key: MARIADB_BACKUP_CRITICAL_WEBHOOK
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
