---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: app-coredns
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
        hosts {
          192.168.0.100 tv.miutaku.local
          192.168.0.117 pve-nucbox-3-wired.miutaku.local
          192.168.0.118 pve-nucbox-3-wifi.miutaku.local
          192.168.0.119 pve-b550m.miutaku.local
          192.168.0.120 gaming-pc.miutaku.local
          192.168.0.122 bastion-01.miutaku.local
          192.168.0.124 work-windows.miutaku.local
          192.168.0.125 mirakurun.miutaku.local
          192.168.0.126 master-01-rke2-server.miutaku.local
          192.168.0.127 master-02-rke2-server.miutaku.local
          192.168.0.128 master-03-rke2-server.miutaku.local
          192.168.0.129 worker-01-rke2-server.miutaku.local
          192.168.0.130 worker-02-rke2-server.miutaku.local
          192.168.0.135 lb-01-rke2.miutaku.local
          192.168.0.136 lb-02-rke2.miutaku.local
          fallthrough
        }
    }
