---
apiVersion: v1
kind: Service
metadata:
  name: coredns-service
  namespace: app-coredns
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.0.201
  labels:
    app: coredns
spec:
  selector:
    app: coredns
  type: LoadBalancer
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: metrics
      port: 9153
      protocol: TCP
      targetPort: 9153
