apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: annict-scraper
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/miutaku/my-infra.git
    targetRevision: main
    path: k8s/pve/annict-scraper
  destination:
    server: https://kubernetes.default.svc
    namespace: app-annict-scraper
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
