apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mirakurun-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/miutaku/my-infra.git
    targetRevision: main
    path: k8s/pve/mirakurun-staging
  destination:
    server: https://kubernetes.default.svc
    namespace: app-mirakurun-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
