apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tnlastation
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/miutaku/my-infra.git
    targetRevision: main
    path: k8s/pve/tnlastation
  destination:
    server: https://kubernetes.default.svc
    namespace: app-tnlastation
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: ffmpeg-worker-encode
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      name: ffmpeg-worker-streaming
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
