apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://github.com/chrissnell/unifi-os-kubernetes.git
      targetRevision: main
      path: chart
      helm:
        releaseName: unifi
        valueFiles:
          - $values/k8s/pve/unifi/values.yaml
        postRenderers:
          - kustomize:
              patches:
                - target:
                    group: apps
                    version: v1
                    kind: Deployment
                    name: unifi-unifi-os-server
                  patch: |-
                    apiVersion: apps/v1
                    kind: Deployment
                    metadata:
                      name: unifi-unifi-os-server
                    spec:
                      template:
                        spec:
                          initContainers:
                            - name: patch-uv-threadpool
                              image: busybox:latest
                              command:
                                - sh
                                - -c
                                - |-
                                  printf 'NODE_ENV="production"\nUV_THREADPOOL_SIZE=4\nNODE_CONFIG_DIR="/usr/share/unifi-core/app/config/:/data/unifi-core/config/overrides/"\n' > /override/unifi-core
                              volumeMounts:
                                - name: env-override
                                  mountPath: /override
                          volumes:
                            - name: env-override
                              emptyDir: {}
                          containers:
                            - name: unifi-os-server
                              volumeMounts:
                                - name: env-override
                                  mountPath: /etc/default/unifi-core
                                  subPath: unifi-core
    - repoURL: https://github.com/miutaku/my-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: unifi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
