apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vmagent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts
      chart: victoria-metrics-agent
      targetRevision: "0.43.0"
      helm:
        releaseName: vmagent
        valueFiles:
          - $values/k8s/pve/vmagent/values.yaml
    - repoURL: https://github.com/miutaku/my-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
