apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: victoria-metrics-backup-credentials
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: victoria-metrics-backup-credentials
    creationPolicy: Owner
  data:
    - secretKey: OCI_NAMESPACE
      remoteRef:
        key: DB_BACKUP_OCI_NAMESPACE
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: DB_BACKUP_OCI_S3_ACCESS_KEY
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: DB_BACKUP_OCI_S3_SECRET_KEY
