apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics-victoria-metrics-single-server
  namespace: monitoring
spec:
  type: ExternalName
  externalName: victoria-metrics-green.monitoring.svc.cluster.local
