all:
  children:
    monitored_vms:
      hosts:
        dev-app-server:
          ansible_host: 192.168.20.101
        nas-01:
          ansible_host: 192.168.20.191
        nas-02:
          ansible_host: 192.168.20.192
    monitored_physical_hosts:
      hosts:
        nut-pi-01:
          ansible_host: 192.168.10.112
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        nut-pi-02:
          ansible_host: 192.168.10.113
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        pve-x570:
          ansible_host: 192.168.0.115
          ansible_user: root
        pve-b550m:
          ansible_host: 192.168.0.119
          ansible_user: root
  vars:
    ansible_user: miutaku
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3
