apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-my-infra-token-secret
  namespace: arc-runners
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: github-my-infra-token-secret
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: GITHUB_MY_INFRA_RUNNER_PAT
