apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arc-runner-reventer-cache
  namespace: arc-runners
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
