apiVersion: v1
kind: Service
metadata:
  name: epgstation
  namespace: app-epgstation
  annotations:
    metallb.universe.tf/loadBalancerIPs: "__EPGSTATION_LB_IP__"
spec:
  type: LoadBalancer
  selector:
    app: epgstation
  ports:
    - name: http
      port: 8888
      targetPort: 8888
    - name: stream
      port: 8889
      targetPort: 8889
