apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - mariadb-secret.yaml
  - mariadb-statefulset.yaml
  - mariadb-service.yaml
  - epgstation-secret.yaml
  - epgstation-configmap.yaml
  - epgstation-deployment.yaml
  - epgstation-service.yaml
