---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-exporter
  namespace: exporter
  labels:
    app: speedtest-exporter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speedtest-exporter
  template:
    metadata:
      labels:
        app: speedtest-exporter
    spec:
      containers:
        - name: speedtest-exporter
          image: ghcr.io/miutaku/speedtest-exporter:latest
          ports:
            - containerPort: 8080
