---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
  namespace: exporter
  labels:
    app: speedtest-exporter
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.202
  selector:
    app: speedtest-exporter
  ports:
    - name: speedtest-exporter
      protocol: TCP
      port: 8080
      targetPort: 8080
