apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tnlastation-secrets
  namespace: app-tnlastation
spec:
  target:
    template:
      engineVersion: v2
      data:
        POSTGRES_PASSWORD: "{{ .postgres_password }}"
        POSTGRES_CONNECTION_STRING: >-
          Host=postgres.infra-db-staging.svc.cluster.local;Port=5432;Database=tnlastation;Username=tnlastation;Password={{ .postgres_password }}
