name: Simple K8s Deploy Test

on:
  push:

jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Workflow was triggered by a push to ${{ github.ref }}."